[[servers]]
  Address = "tcp://78.46.227.60:7770"
  Public = "5eI+WFOaCdMhHY+g+zR11IZV4MBtg+k8jm59FqqHwQY="
  Description = "Ineiti's Cothority-server"

[[servers]]
  Address = "tcp://192.33.210.8:7770"
  Public = "A2vzFuHqbn6Z4LtxNBnRbAtnlL+dxELMTPNsP5Nek88="
  Description = "EPFL Cothority-server"

[[servers]]
  Address = "tcp://5.135.161.91:2000"
  Public = "UsanfHVs5fO+80FABsRVVq63CEwPPkRn3ScQeSeRLFE="
  Description = "Nikkolasg's server serving the cothority"

[[servers]]
  Address = "tcp://159.100.249.178:6879"
  Public = "9nzWwjezfPVlu5U9q07h2HWTsBJmXXsRBJO+6AHonkw="
  Description = "Daeinar's Conode"

[[servers]]
  Address = "tcp://46.101.254.191:6879"
  Public = "YZ0ZigYRtA1XxbwiCis2Vcv+8JLwbtaKeAjAU+HPmNs="
  Description = "Kirill's server"

[[servers]]
  Address = "tcp://139.59.10.242:3000"
  Public = "4OwnNWMX6+XIenC/8orGHYzwhuxSwSLGhUCyAsDTvt8="
  Description = "Brahma-BL1"

[[servers]]
  Address = "tcp://167.160.36.37:3000"
  Public = "Nw0ZhZgLzZ3Vjkgx/lWkCd2LIN+E+IM3AI2jBv4j9dk="
  Description = "sina's conode"
