Simulation = "RandHound"
Servers = 32
Bf = 2
Rounds = 1
RunWait = 3600
CloseWait = 3600
Delay = 100

Hosts, GroupSize
64, 32
96, 32
128, 16
128, 24
128, 32
128, 40
256, 16
256, 24
256, 32
256, 40
512, 16
512, 24
512, 32
512, 40
768, 16
768, 24
768, 32
768, 40
1024, 16
1024, 24
1024, 32
1024, 40
